modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="withereggs"
version="${file.jarVersion}"
displayName="Wither Eggs"
displayURL="http://www.curseforge.com/minecraft/mc-mods/wither-eggs"
authors="IchHabeHunger54"
description='''
Adds spawn eggs for the Wither, the Ender Dragon, the Iron Golem, the Snow Golem, the Illusioner and the Giant.
'''
[[dependencies.withereggs]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.withereggs]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
